srvaroa/labeler

go.mod, pkg/labeler.go, pkg/labeler_test.go
The previous version would fail in some cases with multiple conditions
for a single label depending on the order of evaluation of conditions.
Ref. #11
=> Correct calculation on multiple conditions

README.md
- Many indentations of YAML code block in `README.md` are broken.
- Use the Markdown syntax for code block.
=> Improve YAML highlighting in README.md

README.md
- There are some whitespace characters in `README.md`
- Caused by #18
=> Remove trailing spaces

pkg/labeler.go
- The current `getPrFileNames()` function doesn't work.
- `https://github.com/:owner/:repo/pull/:number.diff` doesn't accept `Authorization` token.
- Closes #19 
- https://stackoverflow.com/questions/35471316/using-curl-how-do-i-download-a-diff-file-from-a-private-repository-on-github
- Use `https://api.github.com/repos/:owner/:repo/pulls/:number` API
- Tested with my project. This works well.
- `github.com/waigani/diffparser` package cannot parse correctly with `renamed` diff.
=> Fix broken getPrFileNames() function

pkg/labeler.go, pkg/labeler_test.go
Allow the specifying of the base branch along with the matching of a
head branch. This is a quite a simple change as we use the same code for
branch matching, but tailor it for base branches.
This is great for my usage, as I can then label new PRs dependant on
where they're going to land, helping priortize and categorize incoming
changes to a repo.
=> Add base branch matching

cmd/action.go, pkg/labeler.go
When triggering via a cron schedule we list all PRs against the current repo and evaluate them
=> feat: allow this to work with a cron schedule

.github/labeler.yml, .github/workflows/main.yml, README.md, cmd/action.go, go.mod, go.sum, pkg/labeler.go
=> Support PullRequestTargetEvent (fixes #13)

README.md
Looking in the code I discovered that there is a condition for the target branch `base-branch` that is not documented.
This PR documents: https://github.com/srvaroa/labeler/pull/23
=> Add undocumented condition `base-branch`

.gitignore, Dockerfile, README.md
* Brings the build down to ~10 seconds from ~26.
* Decouples build from execution, so we facilitate go version upgrades (a recent upgrade do go-github@v50 required go 1.17 but this broke the label executor as ubuntu-latest doesn't support go 1.17 out of the box).
=> Use pre-built binary

README.md, pkg/labeler.go, pkg/labeler_test.go
Mainly a workaround for Go's lack of support to negative-lookahead regex.
This feature allows negating the result of the conditions applied to each label.
=> Allow negating conditions

README.md, cmd/action.go, cmd/action_test.go, pkg/condition_size.go, pkg/labeler.go, pkg/labeler_test.go, test_data/config_v1_composite_size.yml
In retrospect, the previous config for size was not very fortunate as it splits properties that have a semantic relation in two unrelated ones:
- label: M
size-above: 10
size-below: 100
In order to support file exclusions for the size calculation it'd make a cleaner config schema to have all size properties in a single Size node.
This change introduces a `size` node as a condition configuration that replaces `size-above` and `size-below`, while respecting backwards compatibility. Older config files will continue working, but from now on the way to specify the file condition will be:
- label: M
above: 10
below: 100
=> size: composite configuration

.github/workflows/release.yml
Closes #92
Closes #93 
The release workflow is failing (https://github.com/srvaroa/labeler/actions/runs/6465977654) due to the format change of `https://go.dev/VERSION?m=text` API. It is fixed in go-release-action@v1.39 (https://github.com/wangyoucao577/go-release-action/pull/130). This pull request bumps the action version to the latest to include this fix.
Creating another release (maybe 1.6.3) after merging this will solve #92 and #93.
=> ci: Bump wangyoucao577/go-release-action to v1.40

README.md, action.yml, cmd/action.go
Supporting this use case:
It would be great if it supported labeler.yml files that are auto
generated on build time, and only fallback to fetching it through HTTP
if it is not present locally.
=> Support local config file (fix #82)

.github/workflows/build.yml, README.md, cmd/action.go
Explained in the readme. This is mainly useful for our own CI, but can
also be used when running the action.
=> Allow error code on action failure

action.yml, cmd/action.go
=> Add action input for fail_on_error

README.md
=> README: use_local_config needs checkout

pkg/labeler.go
The struct needed an explicit `yaml:"appendOnly"` as camel case is not
the default.
=> Fix config parser for appendOnly

.gitignore, README.md, pkg/condition_age.go, pkg/condition_age_test.go, pkg/labeler.go, pkg/labeler_test.go
=> Support labels based on PR / Issue age

README.md
First of all, thanks for developing and maintaning the actions. It's great!
This is small update in `README.md`.
* Link to the action config file is fixed. Its href was to `action.yaml` file, whereas the actual file is `action.yml`.
* Name of the default config file is updated as well; again `*.yaml` vs. `.yml` issue.
=> Fix inconsistencies in YAML extensions

pkg/condition_author_can_merge.go, pkg/labeler_test.go
=> Fix bug in author_can_merge

pkg/condition_author_can_merge.go, pkg/labeler.go
author-can-merge was not considering all the roles that allow for
committing into the base branch
Fixes: #123
=> Fix can merge with additional roles

README.md, cmd/action_test.go, pkg/condition_size.go, pkg/labeler_test.go, test_data/config_v1_composite_size.yml
=> Size: support regex exclusions

pkg/labeler_test.go, test_data/diff_response
=> Files: tests for issue #33

README.md, cmd/action.go, pkg/condition_author_in_team.go, pkg/labeler.go, pkg/labeler_test.go
=> Support author-in-team

README.md
It seems the correct YAML key is actually `author-in-team` https://github.com/srvaroa/labeler/blob/2673f66494a450dbbe596ae034b761ea47d80104/pkg/labeler.go#L25
=> Fix "Author is member" in README

cmd/action.go, pkg/condition_author_in_team.go, pkg/labeler.go, pkg/labeler_test.go
Use the right GH API to resolve team membership
Fixes #153 
=> Fix author-in-team

README.md, pkg/condition_age.go, pkg/labeler.go, pkg/labeler_test.go
Adds the ability to specify ranges for the `age` matcher. Same as the `last-modified` matcher, this makes use of the same `DurationConfig` struct. Maintains support for the previous string matcher (ie: `age: 8d`), but removes references to it in the documentation and marks it as "deprecated" (so that if we wanted to clean stuff up on the next major version bump, we could remove this).
```yaml
- age: 7d
- age:
at-least: 7d
```
Closes #158
=> Convert age matcher to use a duration config

pkg/condition_ismergeable.go, pkg/labeler_test.go, test_data/create_pr_mergeable_not_clean_payload
Resolves #162
Extends the `mergeable` check to also ensure that the the [mergeable state](https://docs.github.com/en/graphql/reference/enums#mergestatestatus) is `'clean'`. This ensures that the pull request is truly mergeable. This resolves cases where all status checks have passed (`GetMergeable` returns true) but review is required on the PR before merging.
=> Check that MergeableState is clean for mergeable
